name: solar-esg-env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  # Core Data Science
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  # Geospatial & Computer Vision
  - opencv
  - rasterio
  - geopandas
  - shapely
  - osmnx
  # Deep Learning (Explizit mit GPU-Support)
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  # Pip-Pakete
  - pip
  - pip:
    - segmentation-models-pytorch
    - albumentations
    - captum